In [3]:
import numpy as np

In [4]:
#Creating numpy arrays from python lists

my_list = [1,2,3,4,5]

In [10]:
np_list = np.array(my_list)
np_list

array([1, 2, 3, 4, 5])

In [11]:
second_list = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
twod_arr = np.array(second_list)
twod_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#Creating NumPy array using arange() built-in function.
#This generates 10 digits of values from index 0 to 10 with step size 1 excluding 10

my_list = np.arange(10)
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_list = np.arange(0,11,2)
my_list

array([ 0,  2,  4,  6,  8, 10])

In [22]:
#generate a one-dimensional array of seven zeros.
my_zeros = np.zeros(7)
my_zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [24]:
#generate a one-dimensional array of five ones.
my_ones = np.ones(5)
my_ones

array([1., 1., 1., 1., 1.])

In [26]:
#Creating NumPy array using linspace() built-in function
lin_arr = np.linspace(1, 3, 15)
lin_arr

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ])

In [28]:
#Creating an identity matrix in NumPy
my_matrx = np.eye(6)
my_matrx

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
#Generating an array of random numbers in NumPy
my_rand = np.random.rand(4)
my_rand

array([0.64483272, 0.52636371, 0.26692816, 0.2054268 ])

In [31]:
my_rand = np.random.rand(5, 4)
my_rand

array([[0.96939193, 0.79037806, 0.39300324, 0.03536831],
       [0.87319904, 0.33146849, 0.97455476, 0.81504281],
       [0.50688245, 0.67879503, 0.27218944, 0.67715437],
       [0.4372704 , 0.8526408 , 0.18840574, 0.99822201],
       [0.70986619, 0.86242089, 0.79293942, 0.24469819]])

In [33]:
#Converting one-dimensional array to two-dimensional
arr = np.random.rand(25)
arr.reshape(5,5)


array([[0.44515299, 0.04141942, 0.00361319, 0.44884546, 0.03937217],
       [0.73120433, 0.91992013, 0.72591352, 0.44342984, 0.54895841],
       [0.30201267, 0.40079158, 0.3102372 , 0.83013244, 0.55372274],
       [0.82487448, 0.38822417, 0.18889642, 0.75983281, 0.3267844 ],
       [0.33490165, 0.29242672, 0.42840293, 0.09689114, 0.42438035]])

In [34]:
#Locating the maximum and minimum values of a NumPy Array
arr_2 = np.random.randint(0, 20, 10) 
print(arr_2.max()) #This gives the highest value in the array 
print(arr_2.min()) #This gives the lowest value in the array

15
1


In [42]:
my_array = np.arange(0,11)
print(my_array[8])  #This gives us the value of element at index 8
print(my_array[2:6]) #This returns everything from index 2 to 6(exclusive)
print(my_array[:6]) #This returns everything from index 0 to 6(exclusive)
print(my_array[5:]) #This returns everything from index 5 to the end of the array.
print(my_array[:])

8
[2 3 4 5]
[0 1 2 3 4 5]
[ 5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [44]:
two_d_arr = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(two_d_arr[1][2]) #The value 60 appears is in row index 1, and column index 2
print(two_d_arr[0,1] )
print(two_d_arr[:1, :2])           # This returns [[10, 20]]


60
20
[[10 20]]


In [51]:
new_arr = np.arange(5,15)
print(new_arr)
print(new_arr > 10)
print(new_arr[new_arr>10])  #This returns elements greater than 10 [11, 12, 13, 14]

[ 5  6  7  8  9 10 11 12 13 14]
[False False False False False False  True  True  True  True]
[11 12 13 14]


In [53]:
#Broadcasting
my_array[0:3] = 50
my_array

array([50, 50, 50,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
#arithmetic operations on NumPy Arrays
arr = np.arange(1,11)
print(arr)
print(arr * arr)              #Multiplies each element by itself 
print(arr - arr)              #Subtracts each element from itself
print(arr + arr)              #Adds each element to itself
print(arr / arr)              #Divides each element by itself

[ 1  2  3  4  5  6  7  8  9 10]
[  1   4   9  16  25  36  49  64  81 100]
[0 0 0 0 0 0 0 0 0 0]
[ 2  4  6  8 10 12 14 16 18 20]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [58]:
#scalarr operations
arr + 50              #This adds 50 to every element in that array

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [59]:
print(np.sqrt(arr))     #Returns the square root of each element 
print(np.exp(arr))     #Returns the exponentials of each element
print(np.sin(arr))     #Returns the sin of each element
print(np.cos(arr))     #Returns the cosine of each element
print(np.log(arr))     #Returns the logarithm of each element
print(np.sum(arr))     #Returns the sum total of elements in the array
print(np.std(arr))     #Returns the standard deviation of in the array

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
55
2.8722813232690143


In [61]:
mat = np.arange(1,26).reshape(5,5)
print(mat.sum())         #Returns the sum of all the values in mat
print(mat.sum(axis=0))   #Returns the sum of all the columns in mat
print(mat.sum(axis=1))   #Returns the sum of all the rows in mat

325
[55 60 65 70 75]
[ 15  40  65  90 115]
